### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by MechaTech84** [paj28/xssy#23]
I would like to request a Changelog.

It doesn't need to be fancy, it could just be some datetimes and what changed like:

2024-06-25T13:43:00+00:00:
- Added ABC Lab

2024-06-24T08:17:00+00:00:
- Code changes to prevent unintended solution on DEF Lab
- Removed XYZ Lab and reverted points for previous solvers

**Comment by paj28** [comment]
This is a really good idea. I have just pushed an initial version of this, in the "Timeline" tab. Let me know what you think.
