### ISSUE TITLE
Can't submit solutions

### ISSUE THREAD

**Issue by CSpanias** [paj28/xssy#28]
Hi there,

I just discovered the site (awsome work btw!) and I have trouble submitting the payloads in order to mark the labs as solved. I tried the first two, Basic Reflective XSS and Basic DOM XSS, and I got the same error message back:

<img width="317" alt="chrome_fdl32kAQ66" src="https://github.com/user-attachments/assets/3b1e65ec-b752-4e76-8b41-45a1f6e3d1ee">

They payload works locally:

<img width="532" alt="chrome_HHQl4G5X9k" src="https://github.com/user-attachments/assets/50b0dd28-a1b6-4a64-a765-fd36eb65b9ed">

I thought that the labs might be inactive, but I think saw the last post on GitHub discussions just 3 weeks ago, so I assumed that is not the case.

**Comment by paj28** [comment]
I have rebooted the headless browser. I thought this was now being monitored, but the monitoring is clearly not working. Thank-you for reporting :)
